/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inzyme_jmds_DSCrossBar */

#ifndef _Included_com_inzyme_jmds_DSCrossBar
#define _Included_com_inzyme_jmds_DSCrossBar
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_inzyme_jmds_DSCrossBar_fillInCrossBarPins(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_inzyme_jmds_DSCrossBar_route0(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
