/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inzyme_jmds_DSCaptureDeviceManager */

#ifndef _Included_com_inzyme_jmds_DSCaptureDeviceManager
#define _Included_com_inzyme_jmds_DSCaptureDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inzyme_jmds_DSCaptureDeviceManager
 * Method:    fillInDevices
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_inzyme_jmds_DSCaptureDeviceManager_fillInDevices(JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
