/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inzyme_jmds_DSDataSource */

#ifndef _Included_com_inzyme_jmds_DSDataSource
#define _Included_com_inzyme_jmds_DSDataSource
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_inzyme_jmds_DSDataSource_getCrossBar0(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
