/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inzyme_jmds_DSCaptureDeviceInfo */

#ifndef _Included_com_inzyme_jmds_DSCaptureDeviceInfo
#define _Included_com_inzyme_jmds_DSCaptureDeviceInfo
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_inzyme_jmds_DSCaptureDeviceInfo_fillInPins(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
