/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_inzyme_jmds_DSCapturePin */

#ifndef _Included_com_inzyme_jmds_DSCapturePin
#define _Included_com_inzyme_jmds_DSCapturePin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_inzyme_jmds_DSCapturePin
 * Method:    fillInFormats
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_inzyme_jmds_DSCapturePin_fillInFormats(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
